### ISSUE TITLE
Information about the Saildrone variables

### ISSUE THREAD

**Issue by mayajakes** [oceanhackweek/ohw22-proj-front-finder#3]
It would be good to know a bit more about each of the Saildrone variables, e.g. how they are calculated and which ones we might want to look at for front detection. There are a lot! 42 I think. And we haven't looked at the ADCP data yet either, which would be interesting to see how the speed varies in different locations so we can perhaps use that alongside the altimetry gradients to detect frontal jets.

**Comment by sophieclayton** [comment]
I've worked with some saildrone data before, mostly just T, S and Chl from the surface. I think that those would be a good place to start. Getting U and V from the ADCP could be super handy too, to see whether there is a dynamical response at the fronts... in some cases there are T and S fronts, but they compensate each other in density, so no dynamical response.

**Comment by mayajakes** [comment]
In the saildrone data, the variables have MEAN and STDDEV at the end. Is that calculated over the depth range that the saildrone measures?

**Comment by sophieclayton** [comment]
> In the saildrone data, the variables have MEAN and STDDEV at the end. Is that calculated over the depth range that the saildrone measures?

@MackenzieBlanusa - can you help with this?

**Comment by MackenzieBlanusa** [comment]
I'm pretty sure it is the mean and stddev across spatial points. The saildrone collects measurements every few seconds (not sure the exact frequency) and then the data is averaged to create the 1 min, 5 min, and 1 day datasets that are available online. It is not the mean over the depth range.
